# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import senioritylists.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('senioritylists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateTimeField(verbose_name='bid open date')),
                ('close_date', models.DateTimeField(verbose_name='bid close date')),
            ],
        ),
        migrations.CreateModel(
            name='BidChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=2, validators=[senioritylists.models.validate_status])),
                ('available_places', models.IntegerField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.Bid')),
            ],
        ),
        migrations.CreateModel(
            name='BidSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='submission time')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.Bid')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senioritylists.Pilot')),
            ],
        ),
        migrations.CreateModel(
            name='BidType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='BidTypeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=50, verbose_name='option')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('option_true_false', models.BooleanField(verbose_name='option is true/false')),
                ('option_value', models.IntegerField(verbose_name='value')),
                ('bid_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.BidType')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionChoicePriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='priority')),
                ('bid_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.BidChoice')),
                ('bid_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.BidSubmission')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.BidType'),
        ),
        migrations.AddField(
            model_name='bid',
            name='seniority_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senioritylists.SeniorityList'),
        ),
    ]
